// src/types/workflow.ts
export interface FileChangeEntry {
	filePath: string; // Relative path to the workspace root
	changeType: "created" | "modified" | "deleted"; // Type of change
	summary: string; // Human-readable summary generated by diffingUtils
	timestamp: number; // Unix timestamp for chronological ordering
	addedLines?: string[];
	removedLines?: string[];
	diffContent?: string; // Formatted diff content string (lines prefixed with '+', '-', or ' ')
	inversePatch?: string; // Lightweight patch used for easy reversion (usually replaces originalContent)
	originalContent?: string; // Content before modification/deletion
	newContent?: string; // Content after modification/creation
}

export interface RevertibleChangeSet {
	id: string; // Unique ID for the change set (e.g., UUID or hash)
	timestamp: number; // Unix timestamp when the changes were completed/archived
	changes: FileChangeEntry[]; // Array of individual file changes within this set
	planSummary?: string; // Optional summary of the plan that generated these changes
}
