import { WebviewAppState } from "../types/webviewTypes";

export const appState: WebviewAppState = {
	currentAiMessageContentElement: null,
	currentAccumulatedText: "",
	typingBuffer: "",
	typingTimer: null,
	TYPING_SPEED_MS: 50,
	CHARS_PER_INTERVAL: 1,
	activeCommandIndex: -1,
	filteredCommands: [],
	isCommandSuggestionsVisible: false,
	planConfirmationContainer: null,
	confirmPlanButton: null,
	cancelPlanButton: null,
	pendingPlanData: null,
	pendingCommitReviewData: null,
	isApiKeySet: false,
	isLoading: false,
	isAwaitingUserReview: false,
	isCancelling: false,
	isCommitActionInProgress: false,
	isCancellationInProgress: false,
	isPlanExecutionInProgress: false,
	hasRevertibleChanges: false,
	totalKeys: 0,
	activeIndex: -1,
	isTokenUsageVisible: false,
	nextMessageIndex: 0,
	selectedImages: [],
	allWorkspaceFiles: [],
	isRequestingWorkspaceFiles: false,
	currentSuggestionType: "none",
	currentFileSearchQuery: "",
	editingMessageIndex: null,
	isEditingMessage: false,
	currentActiveOperationId: null,
	lastFormattedTokenStats: null,
};
